'use client'
import { useEffect, useState } from 'react'
import { createClient } from '../lib/supabase/client'
const labels: Record<string,string> = { administrador:'Administrador', professor:'Professor', aluno_encarregado:'Aluno / Encarregado' }
type P={id:string;full_name:string;email:string|null;role:string;phone:string|null}
export function AdminUsers({role}:{role:string}){
 const sb=createClient(); const [rows,setRows]=useState<P[]>([]); const [form,setForm]=useState({fullName:'',email:'',phone:'',role:'aluno_encarregado',specialty:'',guardianName:'',guardianPhone:'',guardianEmail:''}); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [msg,setMsg]=useState('')
 async function load(){if(role!=='administrador')return;const {data,error}=await sb.from('profiles').select('id,full_name,email,role,phone').order('full_name');if(error)setError(error.message);else setRows(data||[])} useEffect(()=>{load()},[role]); if(role!=='administrador')return null
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');setMsg('');const r=await fetch('/api/admin/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Erro ao criar acesso.');else{setMsg(d.message||'Convite enviado.');setForm({fullName:'',email:'',phone:'',role:'aluno_encarregado',specialty:'',guardianName:'',guardianPhone:'',guardianEmail:''});load()}setLoading(false)}
 return <section className="section"><div className="peopleHead"><div><div className="eyebrow">Contas</div><h2 style={{margin:'6px 0 4px'}}>Acessos reais</h2><div className="muted">Convites geridos pelo administrador. As palavras-passe ficam no Supabase Auth.</div></div></div>{error&&<div className="error">{error}</div>}{msg&&<div className="success">{msg}</div>}<div className="card" style={{marginTop:16}}><h3 style={{marginTop:0}}>Novo convite</h3><form onSubmit={submit} className="twoFields"><div className="field"><label>Nome</label><input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} required/></div><div className="field"><label>Email</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div className="field"><label>Telefone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Perfil</label><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="aluno_encarregado">Aluno / Encarregado</option><option value="professor">Professor</option><option value="administrador">Administrador</option></select></div>{form.role==='professor'&&<div className="field"><label>Especialidade</label><input value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}/></div>}{form.role==='aluno_encarregado'&&<><div className="field"><label>Nome do encarregado</label><input value={form.guardianName} onChange={e=>setForm({...form,guardianName:e.target.value})}/></div><div className="field"><label>Email do encarregado</label><input type="email" value={form.guardianEmail} onChange={e=>setForm({...form,guardianEmail:e.target.value})}/></div><div className="field"><label>Telefone do encarregado</label><input value={form.guardianPhone} onChange={e=>setForm({...form,guardianPhone:e.target.value})}/></div></>}<div style={{gridColumn:'1/-1'}}><button className="btn primary" disabled={loading}>{loading?'A enviar…':'ENVIAR CONVITE'}</button></div></form></div><div className="card" style={{marginTop:16}}><h3 style={{marginTop:0}}>Utilizadores</h3><div className="leadTable"><div className="leadRow leadHead" style={{gridTemplateColumns:'2fr 1.4fr 1fr 1fr'}}><span>Nome</span><span>Email</span><span>Perfil</span><span>Telefone</span></div>{rows.map(r=><div className="leadRow" style={{gridTemplateColumns:'2fr 1.4fr 1fr 1fr'}} key={r.id}><span>{r.full_name}</span><span>{r.email||'—'}</span><span><span className="pill">{labels[r.role]||r.role}</span></span><span>{r.phone||'—'}</span></div>)}</div></div></section>
}
