'use client'
import {useEffect,useState} from 'react'
import {useSearchParams} from 'next/navigation'
import {createClient} from '../lib/supabase/client'
export function SignupForm(){
 const params=useSearchParams(); const [status,setStatus]=useState(''); const [loading,setLoading]=useState(false); const [instruments,setInstruments]=useState<{id:string;name:string}[]>([])
 useEffect(()=>{createClient().from('instruments').select('id,name').order('name').then(({data})=>setInstruments(data||[]))},[])
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus('');setLoading(true);const f=new FormData(e.currentTarget);const supabase=createClient();const interest=String(f.get('interest_instrument_id')||'')||null;const source=params.get('utm_source')||params.get('source')||'site';const campaign=params.get('utm_campaign')||null;const {error}=await supabase.from('leads').insert({name:String(f.get('name')||'').trim()||null,email:String(f.get('email')||'').trim()||null,phone:String(f.get('phone')||'').trim()||null,preferred_contact:String(f.get('preferred_contact')||'')||null,interest_instrument_id:interest,source,campaign,funnel_stage:'completed',consent_at:new Date().toISOString()});setLoading(false);setStatus(error?`Erro: ${error.message}`:'Recebido. Entramos em contacto consigo brevemente.');if(!error)e.currentTarget.reset()}
 return <form className="form" onSubmit={submit}><div className="eyebrow">Inscrição</div><h2>Quero inscrever-me</h2><p className="muted">Podes deixar campos incompletos. O consentimento é obrigatório.</p><div className="field"><label>Nome</label><input name="name"/></div><div className="field"><label>Instrumento de interesse</label><select name="interest_instrument_id" defaultValue=""><option value="">Escolher…</option>{instruments.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></div><div className="field"><label>Email</label><input name="email" type="email"/></div><div className="field"><label>Telemóvel</label><input name="phone"/></div><div className="field"><label>Preferes contacto por</label><select name="preferred_contact" defaultValue=""><option value="">Escolher…</option><option>Chamada</option><option>Email</option><option>WhatsApp</option></select></div><label style={{display:'flex',gap:10,alignItems:'flex-start',fontSize:13,marginBottom:15}}><input name="consent" type="checkbox" required/> Aceito que a Palco 21 utilize os meus dados para responder ao pedido de inscrição.</label>{status&&<div className={status.startsWith('Erro')?'error':'success'}>{status}</div>}<button className="btn primary" disabled={loading}>{loading?'A ENVIAR…':'ENVIAR INSCRIÇÃO →'}</button></form>
}
