import Link from 'next/link'
import { Suspense } from 'react'
import { SignupForm } from '../../components/SignupForm'
export default function Home(){
 const instruments=['Guitarra','Piano','Baixo','Bateria','Canto','Ukulele']
 return <main><header><div className="wrap nav"><div className="brand">PALCO <span>21</span></div><nav className="navlinks"><a className="hideMobile" href="#aulas">Aulas</a><a className="hideMobile" href="#instrumentos">Instrumentos</a><Link className="btn ghost" href="/login">Área reservada</Link></nav></div></header><div className="wrap"><section className="hero"><div><div className="eyebrow">Escola de música</div><h1>Aprende música.<br/><span style={{color:'var(--accent2)'}}>Toca a tua cena.</span></h1><p>Aulas individuais, professores próximos e uma escola feita para aprenderes, tocar e evoluir ao teu ritmo.</p><div className="chips">{instruments.map(i=><Link href={{pathname:'/',query:{instrument:i.toLowerCase()}}} className="chip" key={i}>{i}</Link>)}</div><a className="btn primary" href="#inscricao">QUERO INSCREVER-ME →</a></div><div className="heroCard"><div className="muted">PALCO 21</div><h2>Uma escola.<br/>Vários caminhos.</h2><p className="muted">Escolhe o instrumento, deixa o contacto que te for mais cómodo e tratamos do resto.</p></div></section><section id="instrumentos" className="section"><h2>Instrumentos</h2><div className="grid">{instruments.map(i=><a href={`#inscricao`} className="card" key={i}><strong>{i}</strong><div className="muted" style={{marginTop:8}}>Aulas individuais · 50 min</div></a>)}</div></section><section id="aulas" className="section"><h2>Como funciona</h2><div className="grid"><div className="card"><strong>1. Inscrição</strong><p className="muted">Deixas os teus dados e escolhes o instrumento.</p></div><div className="card"><strong>2. Contacto</strong><p className="muted">A escola entra em contacto pelo meio que preferires.</p></div><div className="card"><strong>3. Começas</strong><p className="muted">Definimos professor e horário.</p></div></div></section><section id="inscricao" className="section">
  <Suspense fallback={<div className="card">A carregar formulário…</div>}>
    <SignupForm />
  </Suspense>
</section><footer className="section muted"><div className="wrap" style={{padding:0,display:'flex',gap:18,flexWrap:'wrap'}}><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos</Link></div></footer></div></main>
}
